### ISSUE TITLE
Installed Correctly; Cannot Execute Translation

### ISSUE THREAD

**Issue by mattbowlby** [vsetka/deepl-translator-cli#9]
I installed the deepl-translator-cli according to the instructions. If I type `deepl -h` the application provides the help instructions. However, if I type `deepl translate -h` or `deepl translate` and attempt to translate something, I get the following error message:

`
 matt@Matts-MacBook-Air  ~  deepl translate -h                        127 ↵  206  09:18:31
node:internal/child_process:420
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOTDIR
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at spawn (node:child_process:757:9)
    at Command.executeSubCommand (/Users/mattbowlby/.config/yarn/global/node_modules/commander/index.js:546:14)
    at Command.parse (/Users/mattbowlby/.config/yarn/global/node_modules/commander/index.js:471:17)
    at Object.<anonymous> (/Users/mattbowlby/.config/yarn/global/node_modules/deepl-translator-cli/deepl.js:9:4)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'spawn'
}

Node.js v19.6.1
`

## Environment

I am using macOS Ventura (13.1).
nodeJS v19.6.1

**Comment by vsetka** [comment]
Repository no longer maintained
